// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rkYDy0omk2hy6B0QUGvmNHjNO57kzVk',
    appId: '1:867306860412:web:a7c6599df70e55be64fef9',
    messagingSenderId: '867306860412',
    projectId: 'autoaccess-78182',
    authDomain: 'autoaccess-78182.firebaseapp.com',
    storageBucket: 'autoaccess-78182.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VAs9I3xXESzj0Xf4Lnqnu2qBcQVcazk',
    appId: '1:867306860412:android:ac3d4e7cc57ce2ce64fef9',
    messagingSenderId: '867306860412',
    projectId: 'autoaccess-78182',
    storageBucket: 'autoaccess-78182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6XxiKgrepyNFVHg-uBOr9Lb7KFW3nio',
    appId: '1:867306860412:ios:a35190c351c46b3864fef9',
    messagingSenderId: '867306860412',
    projectId: 'autoaccess-78182',
    storageBucket: 'autoaccess-78182.firebasestorage.app',
    androidClientId: '867306860412-9e1pp40mqpdjfqcneilvdnrufjgs93um.apps.googleusercontent.com',
    iosClientId: '867306860412-u725g2n1o4f69u5ast5tc2rb2163tpod.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoAccess',
  );

}