import 'package:auto_access/features/personalization/models/address_model.dart';
import 'package:auto_access/features/personalization/models/user_model.dart';
import 'package:auto_access/features/rent/models/car_model.dart';
import 'package:auto_access/features/rent/models/car_review_model.dart';
import 'package:auto_access/features/rent/models/car_variation_model.dart';
import 'package:auto_access/features/rent/models/category_model.dart';
import 'package:auto_access/features/rent/models/rental_model.dart';
import 'package:auto_access/features/rent/models/rental_shop_category_model.dart';
import 'package:auto_access/features/rent/models/rental_shops_model.dart';
import 'package:auto_access/utility/constants/enums.dart';
import 'package:auto_access/utility/constants/image_strings.dart';
import '../models/banner_model.dart';
import '../models/car_attributes_model.dart';
import '../models/car_category_model.dart';

class DummyData {

  /// -- Banners
  static final List<BannerModel> banners = [
    BannerModel(imageUrl: RImages.appleCarRental, active: true, targetScreen: ''),
    BannerModel(imageUrl: RImages.carRentDiscount,  active: false, targetScreen: '')];

  ///Users
  static final UserModel user = UserModel(
    id: '01',
    firstName: 'Saada',
    lastName: 'AlRahbi',
    username: 'saada01',
    email: 'alrahbisaada@gmail.com',
    phoneNumber: '98583987',
    profilePicture: RImages.userProfile1,
    addresses: [
      AddressModel(
          id: '1',
          name: 'Buthaina AlKindy',
          phoneNumber: '98583987',
          street: 'Maabela',
          city: 'Muscat',
          state: 'Seeb',
          postalCode: '122'),
      AddressModel(
          id: '2',
          name: 'Laith AlHabsi',
          phoneNumber: '98583987',
          street: 'Al Khuwair Al Janubiyyah',
          city: 'Muscat',
          state: 'Al Khuwair',
          postalCode: '133'),
      AddressModel(
          id: '3',
          name: '',
          phoneNumber: '98583987',
          street: 'Al Rusayl',
          city: 'Muscat',
          state: 'Muscat',
          postalCode: '124'),
    ],
  );

  static final List<RentalModel> rentals = [
    RentalModel(
      id: 'R001',
      status: RentalStatus.delivered,
      totalAmount: 35,
      rentDate: DateTime(2023, 10, 12),
      deliveryDate: DateTime(2023, 10, 12),
    ),
    RentalModel(
      id: 'R001',
      status: RentalStatus.returned,
      totalAmount: 35,
      rentDate: DateTime(2023, 10, 12),
      deliveryDate: DateTime(2023, 10, 12),
    ),
    RentalModel(
      id: 'R025',
      status: RentalStatus.delivered,
      totalAmount: 25,
      rentDate: DateTime(2023, 12, 12),
      deliveryDate: DateTime(2023, 12, 12),
    ),
    RentalModel(
      id: 'R005',
      status: RentalStatus.delivered,
      totalAmount: 15,
      rentDate: DateTime(2024, 1, 5),
      deliveryDate: DateTime(2024, 1, 6),
    ),
    RentalModel(
      id: 'R035',
      status: RentalStatus.delivered,
      totalAmount: 50,
      rentDate: DateTime(2024, 01, 1),
      deliveryDate: DateTime(2024, 01, 1),
    ),
    RentalModel(
      id: 'R067',
      status: RentalStatus.cancelled,
      totalAmount: 35,
      rentDate: DateTime(2023, 10, 12),
    ),
  ];


  /// -- List of all Categories
  static final List<CategoryModel> categories = [
  CategoryModel(id: '1', image: RImages.cabriolet, isFeatured: true, name: 'Cabriolet'),
  CategoryModel(id: '3', image: RImages.coupe, isFeatured: true, name: 'Coupe'),
  CategoryModel(id: '4', image: RImages.hatchback, isFeatured: true, name: 'Hatchback'),
  CategoryModel(id: '5', image: RImages.luxury, isFeatured: true, name: 'Luxury'),
  CategoryModel(id: '6', image: RImages.miniVan, isFeatured: true, name: 'MiniVan'),
  CategoryModel(id: '7', image: RImages.pickupC, isFeatured: true, name: 'Pickup truck'),
  CategoryModel(id: '8', image: RImages.sedan, isFeatured: true, name: 'Sedan'),
  CategoryModel(id: '9', image: RImages.sport, isFeatured: true, name: 'Sport'),
  CategoryModel(id: '10', image: RImages.suv, isFeatured: true, name: 'SUV'),
  CategoryModel(id: '2', image: RImages.camperVan, isFeatured: true, name: 'CamperVan'),

    ///Sub categories
    CategoryModel(id: '15', image: RImages.luxury, name: 'Luxury Cars', parentId: '1' , isFeatured: false),
    CategoryModel(id: '17', image: RImages.pickupC, name: 'Pick up Trucks', parentId: '1' , isFeatured: false),
    CategoryModel(id: '18', image: RImages.coupe, name: 'Audi Coupe', parentId: '1' , isFeatured: false),
  ];


  /// -- List of all Rental Shop
  static final List<RentalShopModel> rentalShop = [
    RentalShopModel(id: '1', image: RImages.mas, name: 'Mas Rent A Car', isFeatured: true ),
    RentalShopModel(id: '2', image: RImages.mersad, name: 'Mersad Car Rental', isFeatured: true),
    RentalShopModel(id: '3', image: RImages.bahwan, name: 'Bahwan Tourism Car Rental', isFeatured: true),
    RentalShopModel(id: '4', image: RImages.budget, name: 'Budget Car Rental', isFeatured: true),
    RentalShopModel(id: '5', image: RImages.sixt, name: 'SiXT Rent A Car', isFeatured: true),
    RentalShopModel(id: '6', image: RImages.thrifty, name: 'Thrifty Car Rental', isFeatured: true ),
    RentalShopModel(id: '7', image: RImages.europ, name: 'EuropCar', isFeatured: true),
    RentalShopModel(id: '8', image: RImages.hertz, name: 'Hertz Car Rental', isFeatured: true),
    RentalShopModel(id: '9', image: RImages.avis, name: 'Avis', isFeatured: true),
    RentalShopModel(id: '10', image: RImages.nab, name: 'NAB Rent A Car', isFeatured: true ),
    RentalShopModel(id: '11', image: RImages.apple, name: 'Apple Car Rental', isFeatured: true),
  ];

  ///List of all cars
  static final List<CarModel> cars = [
    CarModel(
        id: '001',
        title: 'Blue Audi',
        availability: 2,
        price: 15,
        isFeatured: true,
        thumbnail: RImages.audi,
        description: 'Blue Audi Car',
        rentalShop: RentalShopModel(id: '2', image: RImages.mersad, name: 'Mersad Car Rental'),
        images: [RImages.audi, RImages.audi2, RImages.audi3, RImages.audi4, RImages.audi5],
        sku: 'ABR4568',
        categoryId: '5',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 15, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 20, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 25, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 30, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 35, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '002',
        title: 'Mercedes - MayBach',
        availability: 2,
        price: 30,
        isFeatured: true,
        thumbnail: RImages.luxury1,
        description: 'White Mercedes - MayBach GLS',
        rentalShop: RentalShopModel(id: '2', image: RImages.mersad, name: 'Mersad Car Rental'),
        images: [RImages.luxury1, RImages.luxury2],
        sku: 'ABR4568',
        categoryId: '5',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 30, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 40, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 60, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 80, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 90, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '003',
        title: 'Mercedes_Benz S Class',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.cabriolet1,
        description: 'Mercedes_Benz_S_Class',
        rentalShop: RentalShopModel(id: '2', image: RImages.mersad, name: 'Mersad Car Rental'),
        images: [RImages.cabriolet1, RImages.cabriolet2, RImages.cabriolet3, RImages.cabriolet4],
        sku: 'ABR4568',
        categoryId: '1',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '004',
        title: 'Audi R8 Coupe',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.coupe1,
        description: 'Audi R8 Coupe. 2017',
        rentalShop: RentalShopModel(id: '2', image: RImages.mersad, name: 'Mersad Car Rental'),
        images: [RImages.coupe1, RImages.coupe2, RImages.coupe3, RImages.coupe4],
        sku: 'ABR4568',
        categoryId: '3',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '005',
        title: 'Toyota Corolla Sedan',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sedan1,
        description: 'Toyota Corolla sedan',
        rentalShop: RentalShopModel(id: '1', image: RImages.mas, name: 'Mas Rent A Car'),
        images: [RImages.sedan1, RImages.sedan2, RImages.sedan3, RImages.sedan4,RImages.sedan5],
        sku: 'ABR4568',
        categoryId: '8',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '006',
        title: 'Ford GT',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sport1,
        description: 'Blue Ford GT 2017',
        rentalShop: RentalShopModel(id: '1', image: RImages.mas, name: 'Mas Rent A Car'),
        images: [RImages.sport1, RImages.sport2, RImages.sport3, RImages.sport4],
        sku: 'ABR4568',
        categoryId: '9',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '007',
        title: 'Chevrolet',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.suv2,
        description: 'Black SUV Chevrolet',
        rentalShop: RentalShopModel(id: '1', image: RImages.mas, name: 'Mas Rent A Car'),
        images: [RImages.suv2, RImages.suv3],
        sku: 'ABR4568',
        categoryId: '10',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '008',
        title: 'Toyota Corolla',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.hatchback1,
        description: 'Toyota Corolla HatchBack',
        rentalShop: RentalShopModel(id: '3', image: RImages.bahwan, name: 'Bahwan Tourism Car Rental'),
        images: [RImages.hatchback1, RImages.hatchback2, RImages.hatchback3, RImages.hatchback4, RImages.hatchback5],
        sku: 'ABR4568',
        categoryId: '4',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '009',
        title: 'Toyota Corolla Sedan',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sedan1,
        description: 'Toyota Corolla sedan',
        rentalShop: RentalShopModel(id: '1', image: RImages.bahwan, name: 'Bahwan Tourism Car Rental'),
        images: [RImages.sedan1, RImages.sedan2, RImages.sedan3, RImages.sedan4,RImages.sedan5],
        sku: 'ABR4568',
        categoryId: '8',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '010',
        title: 'Chevrolet',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.suv2,
        description: 'Black SUV Chevrolet',
        rentalShop: RentalShopModel(id: '1', image: RImages.bahwan, name: 'Bahwan Tourism Car Rental'),
        images: [RImages.suv2, RImages.suv3],
        sku: 'ABR4568',
        categoryId: '10',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '011',
        title: 'Toyota Corolla Sedan',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sedan1,
        description: 'Toyota Corolla sedan',
        rentalShop: RentalShopModel(id: '4', image: RImages.budget, name: 'Budget Car Rental'),
        images: [RImages.sedan1, RImages.sedan2, RImages.sedan3, RImages.sedan4,RImages.sedan5],
        sku: 'ABR4568',
        categoryId: '8',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '012',
        title: 'Toyota Corolla',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.hatchback1,
        description: 'Toyota Corolla HatchBack',
        rentalShop: RentalShopModel(id: '4', image: RImages.budget, name: 'Budget Car Rental'),
        images: [RImages.hatchback1, RImages.hatchback2, RImages.hatchback3, RImages.hatchback4, RImages.hatchback5],
        sku: 'ABR4568',
        categoryId: '4',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '013',
        title: 'Mini Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.minivan1,
        rentalShop: RentalShopModel(id: '4', image: RImages.budget, name: 'Budget Car Rental'),
        images: [RImages.minivan1, RImages.minivan2, RImages.minivan3],
        sku: 'ABR4568',
        categoryId: '6',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '014',
        title: 'Mercedes_Benz S Class',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.cabriolet1,
        description: 'Mercedes_Benz_S_Class',
        rentalShop: RentalShopModel(id: '5', image: RImages.sixt, name: 'SiXT Rent A Car'),
        images: [RImages.cabriolet1, RImages.cabriolet2, RImages.cabriolet3, RImages.cabriolet4],
        sku: 'ABR4568',
        categoryId: '1',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '0015',
        title: 'Ford GT',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sport1,
        description: 'Blue Ford GT 2017',
        rentalShop: RentalShopModel(id: '5', image: RImages.sixt, name: 'SiXT Rent A Car'),
        images: [RImages.sport1, RImages.sport2, RImages.sport3, RImages.sport4],
        sku: 'ABR4568',
        categoryId: '9',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '016',
        title: 'Toyota Corolla',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.hatchback1,
        description: 'Toyota Corolla HatchBack',
        rentalShop: RentalShopModel(id: '5', image: RImages.sixt, name: 'SiXT Rent A Car'),
        images: [RImages.hatchback1, RImages.hatchback2, RImages.hatchback3, RImages.hatchback4, RImages.hatchback5],
        sku: 'ABR4568',
        categoryId: '4',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '017',
        title: 'Hyundai Camper Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.campervan,
        description: 'White Hyundai Camper Van.',
        rentalShop: RentalShopModel(id: '6', image: RImages.thrifty, name: 'Thrifty Car Rental'),
        images: [RImages.campervan, RImages.campervan2],
        sku: 'ABR4568',
        categoryId: '2',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 40, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 45, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 55, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 65, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 80, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '018',
        title: 'Chevrolet',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.suv2,
        description: 'Black SUV Chevrolet',
        rentalShop: RentalShopModel(id: '6', image: RImages.thrifty, name: 'Thrifty Car Rental'),
        images: [RImages.suv2, RImages.suv3],
        sku: 'ABR4568',
        categoryId: '10',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '019',
        title: 'Mini Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.minivan1,
        rentalShop: RentalShopModel(id: '6', image: RImages.thrifty, name: 'Thrifty Car Rental'),
        images: [RImages.minivan1, RImages.minivan2, RImages.minivan3],
        sku: 'ABR4568',
        categoryId: '6',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '020',
        title: 'Toyota Corolla Sedan',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sedan1,
        description: 'Toyota Corolla sedan',
        rentalShop: RentalShopModel(id: '7', image: RImages.europ, name: 'EuropCar'),
        images: [RImages.sedan1, RImages.sedan2, RImages.sedan3, RImages.sedan4,RImages.sedan5],
        sku: 'ABR4568',
        categoryId: '8',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '021',
        title: 'Hyundai Camper Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.campervan,
        description: 'White Hyundai Camper Van.',
        rentalShop: RentalShopModel(id: '7', image: RImages.europ, name: 'EuropCar'),
        images: [RImages.campervan, RImages.campervan2],
        sku: 'ABR4568',
        categoryId: '2',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 40, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 45, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 55, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 65, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 80, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '022',
        title: 'Hyundai Pickup',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.pickup2_,
        description: 'Hyundai Pickup.',
        rentalShop: RentalShopModel(id: '7', image: RImages.europ, name: 'EuropCar'),
        images: [RImages.pickup0, RImages.pickup2_, RImages.pickup_, RImages.pickup, RImages.pickup1, RImages.pickup2],
        sku: 'ABR4568',
        categoryId: '7',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '023',
        title: 'Hyundai Pickup',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.pickup2_,
        description: 'Hyundai Pickup.',
        rentalShop: RentalShopModel(id: '8', image: RImages.hertz, name: 'Hertz Car Rental'),
        images: [RImages.pickup0, RImages.pickup2_, RImages.pickup_, RImages.pickup, RImages.pickup1, RImages.pickup2],
        sku: 'ABR4568',
        categoryId: '7',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '024',
        title: 'Hyundai Camper Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.campervan,
        description: 'White Hyundai Camper Van.',
        rentalShop: RentalShopModel(id: '8', image: RImages.hertz, name: 'Hertz Car Rental'),
        images: [RImages.campervan, RImages.campervan2],
        sku: 'ABR4568',
        categoryId: '2',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 40, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 45, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 55, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 65, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 80, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '0025',
        title: 'Ford GT',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sport1,
        description: 'Blue Ford GT 2017',
        rentalShop: RentalShopModel(id: '8', image: RImages.hertz, name: 'Hertz Car Rental'),
        images: [RImages.sport1, RImages.sport2, RImages.sport3, RImages.sport4],
        sku: 'ABR4568',
        categoryId: '9',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '026',
        title: 'Mercedes_Benz S Class',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.cabriolet1,
        description: 'Mercedes_Benz_S_Class',
        rentalShop: RentalShopModel(id: '9', image: RImages.avis, name: 'Avis'),
        images: [RImages.cabriolet1, RImages.cabriolet2, RImages.cabriolet3, RImages.cabriolet4],
        sku: 'ABR4568',
        categoryId: '1',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '027',
        title: 'Audi R8 Coupe',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.coupe1,
        description: 'Audi R8 Coupe. 2017',
        rentalShop: RentalShopModel(id: '9', image: RImages.avis, name: 'Avis'),
        images: [RImages.coupe1, RImages.coupe2, RImages.coupe3, RImages.coupe4],
        sku: 'ABR4568',
        categoryId: '3',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '0028',
        title: 'Ford GT',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sport1,
        description: 'Blue Ford GT 2017',
        rentalShop: RentalShopModel(id: '9', image: RImages.avis, name: 'Avis'),
        images: [RImages.sport1, RImages.sport2, RImages.sport3, RImages.sport4],
        sku: 'ABR4568',
        categoryId: '9',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '0029',
        title: 'Ford GT',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.sport1,
        description: 'Blue Ford GT 2017',
        rentalShop: RentalShopModel(id: '10', image: RImages.nab, name: 'NAB Rent A Car'),
        images: [RImages.sport1, RImages.sport2, RImages.sport3, RImages.sport4],
        sku: 'ABR4568',
        categoryId: '9',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 30, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 35, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 40, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 45, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 50, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '030',
        title: 'Mercedes - MayBach',
        availability: 2,
        price: 30,
        isFeatured: true,
        thumbnail: RImages.luxury1,
        description: 'White Mercedes - MayBach GLS',
        rentalShop: RentalShopModel(id: '10', image: RImages.nab, name: 'NAB Rent A Car'),
        images: [RImages.luxury1, RImages.luxury2],
        sku: 'ABR4568',
        categoryId: '5',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 30, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 40, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 60, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 80, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 90, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '031',
        title: 'Audi R8 Coupe',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.coupe1,
        description: 'Audi R8 Coupe. 2017',
        rentalShop: RentalShopModel(id: '10', image: RImages.nab, name: 'NAB Rent A Car'),
        images: [RImages.coupe1, RImages.coupe2, RImages.coupe3, RImages.coupe4],
        sku: 'ABR4568',
        categoryId: '3',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 25, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 35, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 40, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 50, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 55, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 65, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '032',
        title: 'Chevrolet',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.suv2,
        description: 'Black SUV Chevrolet',
        rentalShop: RentalShopModel(id: '11', image: RImages.apple, name: 'Apple Car Rental'),
        images: [RImages.suv2, RImages.suv3],
        sku: 'ABR4568',
        categoryId: '10',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '033',
        title: 'Mini Van',
        availability: 2,
        price: 25,
        isFeatured: true,
        thumbnail: RImages.minivan1,
        rentalShop: RentalShopModel(id: '11', image: RImages.apple, name: 'Apple Car Rental'),
        images: [RImages.minivan1, RImages.minivan2, RImages.minivan3],
        sku: 'ABR4568',
        categoryId: '6',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 20, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 25, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 30, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 35, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 40, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 45, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
    CarModel(
        id: '034',
        title: 'Mercedes - MayBach',
        availability: 2,
        price: 30,
        isFeatured: true,
        thumbnail: RImages.luxury1,
        description: 'White Mercedes - MayBach GLS',
        rentalShop: RentalShopModel(id: '11', image: RImages.apple, name: 'Apple Car Rental'),
        images: [RImages.luxury1, RImages.luxury2],
        sku: 'ABR4568',
        categoryId: '5',
        carAttributes: [CarAttributeModel(name:'Duration', values: ['1 Day', '2 Days', '3 Days', '4 Days', '5 Days', '1 Week']),],
        carVariations: [
          CarVariationModel(id: '1', price: 30, attributeValues: {'Duration' : '1 Day'}),
          CarVariationModel(id: '2', price: 40, attributeValues: {'Duration' : '2 Day'}),
          CarVariationModel(id: '3', price: 50, attributeValues: {'Duration' : '3 Day'}),
          CarVariationModel(id: '4', price: 60, attributeValues: {'Duration' : '4 Day'}),
          CarVariationModel(id: '5', price: 80, attributeValues: {'Duration' : '5 Day'}),
          CarVariationModel(id: '6', price: 90, attributeValues: {'Duration' : '1 Week'}),
        ]
    ),
  ];

  static List<RentalShopCategoryModel> rentalShopCategory = [
    RentalShopCategoryModel(rentalShopId: '1', categoryId: '8'),
    RentalShopCategoryModel(rentalShopId: '1', categoryId: '9'),
    RentalShopCategoryModel(rentalShopId: '1', categoryId: '10'),
    RentalShopCategoryModel(rentalShopId: '2', categoryId: '1'),
    RentalShopCategoryModel(rentalShopId: '2', categoryId: '3'),
    RentalShopCategoryModel(rentalShopId: '2', categoryId: '5'),
    RentalShopCategoryModel(rentalShopId: '3', categoryId: '4'),
    RentalShopCategoryModel(rentalShopId: '3', categoryId: '8'),
    RentalShopCategoryModel(rentalShopId: '3', categoryId: '10'),
    RentalShopCategoryModel(rentalShopId: '4', categoryId: '8'),
    RentalShopCategoryModel(rentalShopId: '4', categoryId: '4'),
    RentalShopCategoryModel(rentalShopId: '4', categoryId: '6'),
    RentalShopCategoryModel(rentalShopId: '5', categoryId: '1'),
    RentalShopCategoryModel(rentalShopId: '5', categoryId: '4'),
    RentalShopCategoryModel(rentalShopId: '5', categoryId: '9'),
    RentalShopCategoryModel(rentalShopId: '6', categoryId: '2'),
    RentalShopCategoryModel(rentalShopId: '6', categoryId: '6'),
    RentalShopCategoryModel(rentalShopId: '6', categoryId: '10'),
    RentalShopCategoryModel(rentalShopId: '7', categoryId: '2'),
    RentalShopCategoryModel(rentalShopId: '7', categoryId: '7'),
    RentalShopCategoryModel(rentalShopId: '7', categoryId: '8'),
    RentalShopCategoryModel(rentalShopId: '8', categoryId: '2'),
    RentalShopCategoryModel(rentalShopId: '8', categoryId: '7'),
    RentalShopCategoryModel(rentalShopId: '8', categoryId: '9'),
    RentalShopCategoryModel(rentalShopId: '9', categoryId: '3'),
    RentalShopCategoryModel(rentalShopId: '9', categoryId: '5'),
    RentalShopCategoryModel(rentalShopId: '9', categoryId: '9'),
    RentalShopCategoryModel(rentalShopId: '10', categoryId: '5'),
    RentalShopCategoryModel(rentalShopId: '10', categoryId: '6'),
    RentalShopCategoryModel(rentalShopId: '10', categoryId: '10'),

  ];

  static List<CarCategoryModel> carCategories = [
    CarCategoryModel(carId: '001', categoryId: '5'),
    CarCategoryModel(carId: '002', categoryId: '5'),
    CarCategoryModel(carId: '003', categoryId: '1'),
    CarCategoryModel(carId: '004', categoryId: '3'),
    CarCategoryModel(carId: '005', categoryId: '8'),
    CarCategoryModel(carId: '006', categoryId: '9'),
    CarCategoryModel(carId: '007', categoryId: '10'),
    CarCategoryModel(carId: '008', categoryId: '4'),
    CarCategoryModel(carId: '009', categoryId: '8'),
    CarCategoryModel(carId: '010', categoryId: '10'),
    CarCategoryModel(carId: '011', categoryId: '8'),
    CarCategoryModel(carId: '012', categoryId: '4'),
    CarCategoryModel(carId: '013', categoryId: '6'),
    CarCategoryModel(carId: '014', categoryId: '1'),
    CarCategoryModel(carId: '015', categoryId: '9'),
    CarCategoryModel(carId: '016', categoryId: '4'),
    CarCategoryModel(carId: '017', categoryId: '2'),
    CarCategoryModel(carId: '018', categoryId: '10'),
    CarCategoryModel(carId: '019', categoryId: '6'),
    CarCategoryModel(carId: '020', categoryId: '8'),
    CarCategoryModel(carId: '021', categoryId: '2'),
    CarCategoryModel(carId: '022', categoryId: '7'),
    CarCategoryModel(carId: '023', categoryId: '7'),
    CarCategoryModel(carId: '024', categoryId: '2'),
    CarCategoryModel(carId: '025', categoryId: '9'),
    CarCategoryModel(carId: '026', categoryId: '1'),
    CarCategoryModel(carId: '027', categoryId: '3'),
    CarCategoryModel(carId: '028', categoryId: '9'),
    CarCategoryModel(carId: '029', categoryId: '9'),
    CarCategoryModel(carId: '030', categoryId: '5'),
    CarCategoryModel(carId: '031', categoryId: '3'),
    CarCategoryModel(carId: '032', categoryId: '10'),
    CarCategoryModel(carId: '033', categoryId: '6'),
    CarCategoryModel(carId: '034', categoryId: '5'),

  ];


 static final List<CarReviewModel> carReviews = [
   CarReviewModel(
   id: '01',
    userId: '001',
    userName: 'Buthaina AlKindy',
    ratings: 4.5,
    timestamp: DateTime.now(),
    shopTimestamp: DateTime.now(),
    userImageUrl: RImages.userProfile1,
     comment: 'The user interface of the app is quite intuitive, I was able to browse multiple rental shops and rent my desire car',
     shopComment: 'Thank you so much for your kind words, Buthaina! We are delighted to hear about your smooth experience with the app. We always strive to offer an intuitive interface for our users. Stay tuned for more updates!',
   ),

   CarReviewModel(
    id: '02',
    userId: '002',
    userName: 'Laith AlHabsi',
    ratings: 5,
    timestamp: DateTime.now(),
    shopTimestamp: DateTime.now(),
    userImageUrl: RImages.userProfile2,
    comment: 'I am genuinely impressed with the app design and the variety of cars available. The integration of multiple rental shops in Muscat makes renting cars easier',
    shopComment: 'Thank you so much Laith!, We are thrilled to hear you are enjoying the app and finding your preferred car. Our goal is to make your rental experience as efficient and pleasant as possible. Keep exploring, and enjoy your preferred rental vehicle',
   ),

   CarReviewModel(
     id: '03',
     userId: '003',
     userName: 'Nassor AlKindi',
     ratings: 5,
     timestamp: DateTime.now(),
     shopTimestamp: DateTime.now(),
     userImageUrl: RImages.userProfile3,
     comment: 'The App is quite amazing. The cars are in good condition and the rental shop are trustworthy. Looking forward for more features in the future',
     shopComment: 'Thank you for your feedback Nassor!, We are thrilled to hear you loved the app.  We are constantly working on introducing new features, so keep an eye out for the next update! ',
   ),
 ];


  /// -- Sorting Filters for search
  static final sortingFilters = [
    SortFilterModel(id: '1', name: 'Name'),
    SortFilterModel(id: '2', name: 'Lowest Price'),
    SortFilterModel(id: '3', name: 'Most Popular'),
    SortFilterModel(id: '4', name: 'Highest Price'),
    SortFilterModel(id: '5', name: 'Newest'),
    SortFilterModel(id: '6', name: 'Most Suitable'),
  ];

}

class SortFilterModel {
  String id;
  String name;

  SortFilterModel({required this.id, required this.name});
}